### ISSUE TITLE
Provide additional checksum verification link

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/rockylinux.org-gatsby#412]
#### Description

Our tier 0 mirror used to contain CHECKSUM.sig files for each checksum file. This is no longer the case with Rocky Linux 9. Instead, all CHECKSUM's will be available in this repository with signed commits: https://github.com/rocky-linux/checksums - We would like to see a checksum verification link on the download page in some capacity.

Due to how the new build system operates, we are not able to sign files adhoc with keykeeper, and thus, all checksums will be handled in the aforementioned repository with signed commits using our rockylinux.org or resf.org mail addresses.

#### Screenshots

![image](https://user-images.githubusercontent.com/11469736/179067211-21cd95a4-0da7-40b9-ad40-76a4dd79e13f.png)
![image](https://user-images.githubusercontent.com/11469736/179067280-c774c7ae-5092-449e-a50a-b138f7ed8931.png)

#### Files

https://github.com/rocky-linux/checksums

**Comment by fuzzy9000** [comment]
I hope I'm not hijacking this issue, but I would like to suggest that the existing Checksum links on the Download page be changed to point to the files in this new GitHub repository. (Thanks BTW for creating it!)

As I noted previously in a [forum thread](https://forums.rockylinux.org/t/checksum-file-being-downloaded-from-mirror-site/6394), the ISO and CHECKSUM links on the Download page currently point to the same server. Verifying an ISO using a CHECKSUM file downloaded from the same server may not detect malicious tampering, because if an attacker were able to infiltrate that one server, they could replace the ISO and CHECKSUM files at the same time.

Other OS distributions (e.g., Fedora, CentOS, Ubuntu, FreeBSD) typically supply their ISOs and checksums from different servers. This makes an attacker's job more difficult, as they must compromise multiple servers in order to tamper with the ISOs without users noticing a checksum mismatch.

Linking to `github.com` in particular seems advantageous since GitHub is hosted on totally separate infrastructure. An attack on Rocky Linux servers could not touch GitHub, and vice versa.
