### ISSUE TITLE
Missing Translation - French

### ISSUE THREAD

**Issue by payagej** [rocky-linux/rockylinux.org-gatsby#97]
## Describe the bug

Missing Link on French version.

- `links.status` > Status des services
- `links.partners` > Partenaires
- `links.download` > Télécharger

## To Reproduce

Go on https://rockylinux.org/fr and see yourself.

## Expected behavior

See above.

**Comment by FoggyMtnDrifter** [comment]
Hey there! My comment is specifically targeted towards #123's description. If you're not seeing translations for a language and you know the language, feel free to contribute your own translations! We welcome these contributions!

Until we get a collaborative translation tool setup, you can open a PR for this. For now, we're also requiring that another community member who natively speaks the language approve of the PR before we will merge. Hope that helps!

Regarding this specific issue's description (#97), that issue has been resolved.

I'm going to close this issue since the issue described above has been resolved and translations aren't really something the web team can resolve (unless of course they're native speakers), but instead relies on community-led translations.
